= Application Configuration and Spring Cloud Config

This lab will walk through the process of configuring a Spring app using properies.  Then we'll explore using a Spring Cloud Config server for centralized property management.  The repository will be located in a repo on github.  If you have git available locally, you can use your own local version.

== Setup

You can continue on with the greeting-service from lab02 or load the starter in lab04.  The starter has removed the info/health/metrics.

Load the greeting-service project into STS/Eclipse

[source, bash]
---------------------------------------------------------------------
cn-workshop:
├── labs
│   ├── lab04
│   │   ├── greeting-service
---------------------------------------------------------------------

== Using Local Properties

In this part of the lab we'll focus on using properties as defined in the and passed from the environment.

=== Load properties from application.yml

. Add the property app.greeting in _application.yml_
+
[source,yaml]
.application.yml
---------------------------------------------------------------------
app:
  greeting: hello, world
---------------------------------------------------------------------

. Modify the Greeting class to load the propery or use a default value if it's not found.
+
[source, java]
.Greeting.java
---------------------------------------------------------------------
package io.pivotal;

import org.springframework.beans.factory.annotation.Value;

public class Greeting {
  @Value("${app.greeting:Doh!}")
  public String greeting;
}
---------------------------------------------------------------------

. Run the application and see that it returns the expected value.

=== Change behavior with Profiles

. Create a new file application-new.yml in the resources directory.  Override the greeting property.
+
[source,yaml]
.application-new.yml
---------------------------------------------------------------------
app:
  greeting: hello, new world
---------------------------------------------------------------------

. Rebuild the application so it has the new property file.  Run the application setting the Spring Profile to "new"
+
[source,bash]
----
$ mvn clean package
$ java -jar target/greeting-service-0.0.1-SNAPSHOT.jar --spring.profiles.active=new
----

. See that the property has been picked up from the profile

. Now look at the properties in the environment
+
http://localhost:8080/env

Notice that you can see the properties coming from both the files.

=== Set property from the CLI

. Launch the applicaiton by setting the property on the CLI.  No reason to rebuild.
+
----
$ java -jar target/greeting-service-0.0.1-SNAPSHOT.jar --spring.profiles.active=new --app.greeting=hello-cli
----

. See that the propery is now set to the value passed to the app.  Parameters from the environment take precedence over those contained in property files bundled in the app.  This is a good way to set things at run time based on the deployment environment.  You can also use Environment variables.  For our example the env var would be APP_GREETING.

== Using Properties from a Service

In this part of the lab we'll use properties retrieved from a server backended by a git repository.

=== Set up config-server

. Load the config-server project into STS/Eclipse
+
[source, bash]
---------------------------------------------------------------------
cn-workshop
├── scs-servers
│   ├── config-server
---------------------------------------------------------------------

. Review pom.xml. By adding `spring-cloud-config-server` to the classpath, the application has the libraries available so it can run as a Config Server.
+
[source, xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-config-server</artifactId>
</dependency>
----

. The application is turned into a Config Server with the @EnableConfigServer
+
[source, java]
.ConfigServerApplication.java
---------------------------------------------------------------------
@SpringBootApplication
@EnableConfigServer
public class ConfigServerApplication {

    public static void main(String[] args) {
        SpringApplication.run(ConfigServerApplication.class, args);
    }
}
---------------------------------------------------------------------

. The Config Server is pointed to a git repository via its properties
+
[source, yaml]
.application.yml
---------------------------------------------------------------------
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sdeeg-pivotal/app-config
#          uri: ${HOME}/dev/app-config
---------------------------------------------------------------------

. Open a terminal window and start the `config-server`, or launch from Boot Dashboard.  EG:
+
----
$ mvn clean spring-boot:run
----

Your Config Server will be running locally once you see a *“Started ConfigServerApplication…”* message.

. Open a browser window and fetch the following url: http://localhost:8888/greeting-service/default

*What Just Happened*

The `config-server` exposes several endpoints to fetch configuration.

In this case, we are manually calling one of those endpoints `/{application}/{profile}[/{label}]` to fetch configuration. We substituted our example client application `hello-world` as the {application} and the default profile as the {profile}. We didn’t specify the label to use so master is assumed. In the returned document, we see the configuration file `hello-world.yml` listed as a `propertySource` with the associated key/value pair. This is just an example, as you move through the lab you will add configuration for `greeting-config` (our client application).

=== Configure Greeting Service to consume the remote config

. Add the config client in _pom.xml_.  Since we didn't use the initializer to do this, we'll also need to add the dependancy management for Spring Cloud Services.  These additions will also allow the app to work with a PCF based Config Service.
+
[source, xml]
---------------------------------------------------------------------
<!-- put in dependencies block --/>
    <dependency>
      <groupId>io.pivotal.spring.cloud</groupId>
      <artifactId>spring-cloud-services-starter-config-client</artifactId>
    </dependency>
<!-- end --/>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>Dalston.RC1</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>io.pivotal.spring.cloud</groupId>
        <artifactId>spring-cloud-services-dependencies</artifactId>
        <version>1.4.1.RELEASE</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <repositories>
    <repository>
      <id>spring-milestones</id>
      <name>Spring Milestones</name>
      <url>https://repo.spring.io/milestone</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
  </repositories>
---------------------------------------------------------------------

. Add the following properties
+
[source, yaml]
.application.yml
---------------------------------------------------------------------
#SCS enables Spring Security by default, so we need to turn it off
security:
  basic:
    enabled: false
#Set the application's name so the Config Server can identify it
spring:
  application:
    name: greeting-service
#  cloud:
#    config:
#      uri: ${vcap.services.config-service.credentials.uri:http://localhost:8888}
---------------------------------------------------------------------

. Start *greeting-service* and observe the top of the log output where it show attaching to the config server.
+
[source,bash]
---------------------------------------------------------------------
2016-06-16 01:24:53.034  INFO 16463 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8888
2016-06-16 01:24:53.792  INFO 16463 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Located environment: name=greeting-service, profiles=[default], label=null, version=0fedb371c8f7f7b7c787348e1ad783c2e8dd3465
---------------------------------------------------------------------

. Test the service by hitting the URL: http://localhost:8080/greeting


*Congratulations!* You’ve just added application configuration that is controllable and can be centrally managed.
