= Spring Cloud Service Discovery and Proxying

The Eureka service allows services to discover each other.  In this exercise we'll start with the greeting-service from lab04, and will register it with a local instance of Eureka (Service Registry) that we create.  From there we'll move on to a "front end" server that will consume the output of the Greeting Service by looking it in the registry and then automatically creating a proxy for it using Zuul (Micro-proxy).

== Registering the Greeting Service

The first part of the lab will create an instance of a Service Registry (Eureka), and connect our existing Greeting Service to it.

=== Setup Local Service Registry

Like the Config Server in Lab04, we'll use a local Eureka Service Registry.  A project is available to use.

. Load the registration-server project into STS
+
[source, bash]
---------------------------------------------------------------------
cn-workshop
├── scs-servers
│   ├── registry-server
---------------------------------------------------------------------

. Review the `service-registry/pom.xml` file. By adding spring-cloud-starter-eureka-server to the classpath this application is eligible to embed an Eureka server.

[source, xml]
--------
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-eureka-server</artifactId>
    </dependency>
--------

. The application is turned into a Service Registry by adding @EnableEurekaServer to the main app file.
+
[source,java]
.RegistrationServerApplication.java
----
package io.pivotal;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.netflix.eureka.server.EnableEurekaServer;

@SpringBootApplication
@EnableEurekaServer
public class RegistrationServerApplication {
  public static void main(String[] args) {
    SpringApplication.run(RegistrationServerApplication.class, args);
  }
}
----

. Open up application.yml and observe the following properties
+
[source, yaml]
.application.yml
---------------------------------------------------------------------
server:
  port: ${PORT:8761}
spring:
  application:
    name: registry-server
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
---------------------------------------------------------------------

NOTE: About Eureka

Eureka is designed for peer awareness (running multiple instances with knowledge of each other) to further increase availability. Because of this, Eureka is not only a server but a client as well. Therefore, Eureka Servers will be clients to each other. Eureka Server A ⇄ Eureka Server B.

For the purposes of this lab, we will simplify that configuration to run in standalone mode.

Standlalone mode still offers a high degree of resilience with:

* Heartbeats between the client and server to keep registrations up to date
* Client side caching, so that clients don’t go to Eureka for every lookup
* By running in Pivotal Cloud Foundry which is designed to keep applications up by design
* With the above configuration, we have configured Eureka to run in standalone mode.

. Open a new terminal window. Start the `service-registry`.
```bash
$ cd service-registry
$ mvn clean spring-boot:run
```
. Verify the `service-registry` is up. Browse to http://localhost:8761 to see the Eureka dashboard.

TIP: The Eureka Dashboard may report a warning, because we aren’t setup with multiple peers. This can safely be ignored. warning

=== Modify Greeting Service to register with Eureka

. Either continue on with the greeting-service from lab04, or use the starter in the lab05 directory.
+
[source, bash]
---------------------------------------------------------------------
cn-workshop:
├── labs
│   ├── lab05
│   │   ├── greeting-service
---------------------------------------------------------------------

. Open pom.xml and add the Eureka client library
+
[source, xml]
---------------------------------------------------------------------
    <dependency>
      <groupId>io.pivotal.spring.cloud</groupId>
      <artifactId>spring-cloud-services-starter-service-registry</artifactId>
    </dependency>
---------------------------------------------------------------------

. Enable the Greeting Service to register.  Since this is an application configuration we add the appropriate annotation (@EnableDiscoveryClient) to the Configuration class.
+
[source,java]
.GreetingServiceConfig.java
----
package io.pivotal.config;

import org.springframework.cloud.client.discovery.EnableDiscoveryClient;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import io.pivotal.dom.Greeting;

@Configuration
@EnableDiscoveryClient
public class GreetingServiceConfig {

  @Bean
  public Greeting createGreeting() {
    return new Greeting();
  }
}
----

. Start the Greeting Service

. After the a few moments, check the registry dashboard link:http://localhost:8761/[here]. Confirm the GreetingService is registered. 


== Greeting UI Server

We expand the application topology by bringing up a UI.  This is a server that ultimately will deliver a JavaScript "SPA" application to the brower, then proxy requests to the backend Greeting Service.  For now it'll just work as a micro-proxy.

=== Load the Greeting UI Server

. Load the greeting-ui project into STS
+
[source, bash]
---------------------------------------------------------------------
cn-workshop:
├── labs
│   ├── lab05
│   │   ├── greeting-ui
---------------------------------------------------------------------

. Open pom.xml and notice the starters that were used.  Especially Eureka and Zull (which are new).

. In the Config class enable the application to discover services and automatically proxy requests to it with Zuul.
+
[source,java]
.GreetingUIConfig.java
----
package io.pivotal.config;

import org.springframework.context.annotation.Configuration;

@Configuration
@EnableDiscoveryClient
@EnableZuulProxy
public class GreetingUIConfig {
}
----

. Set the port and application name in the properties.  (Also turn off security.)
+
[source,yaml]
--------
server:
  port: ${PORT:8081}
spring:
  application:
    name: greeting-ui
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
--------

. Start the application
+
[source,bash]
------------
$ mvn spring-boot:run
------------

. Hit the page at http://localhost:8081/greeting-service/greeting

The Zuul proxy retrievs the list of services from Eureka, and creates a proxy for them as though they were hosted on the server delivering the UI.  This means there aren't the Cross Site Request Forgery issues that you have when you have to hit the services directly.  Security can be added with Spring Session to validate tokens across services.

*Congratulations!* You’ve just learned how to use Spring Cloud Service Registration, Discovery, and Micro-Proxying.
